# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d0c77fabf89b5daf472a75ea4f2bf36f81958cee77c6459a8d243e8dffb72d5ef491989fd0340be22abbf80107f9c1933aa3aa73079953216a693dfba32aa76

test:
  secret_key_base: 9f91f61281b17046203105208017464ae47f8ae47db2196de7680bc0436f62e3d8a1f842572ba2bfd3306f9c43a0525e287f4b63771c1d7ffd40f0ce966e33e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
